### ISSUE TITLE
Can you make VGG16.model available? 

### ISSUE THREAD

**Issue by apple2373** [mitmul/chainer-faster-rcnn#15]
Is it possible to get VGG16.model for training? I want to train the object detector but cannot prepare the nvidia-docker because I do not have root privilege in my GPU environment.

**Comment by mitmul** [comment]
@apple2373 Yeah, I can send you the model by e-mail later.

**Comment by apple2373** [comment]
Sure. I commented here because it might be helpful for other users if you make it public, but sending via email is enough for me. Thank you so much.

**Comment by mitmul** [comment]
Well, actually Chainer now can import .caffemodel **without Caffe** using `links.CaffeFunction`, so the shell script using docker in this repo is never needed anymore ;) Just downloading the .caffemodel file and run the below script is enough to get Chainer model and save and then use for fine-tuning.

### Download `.caffemodel`

```bash
wget http://www.robots.ox.ac.uk/%7Evgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel
```

### Load it using **Caffe emulator** of Chainer (As for VGG16, old approach)

```python
import pickle
from chainer.links.caffe import CaffeFunction

vgg16 = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
pickle.dump(vgg16, open('VGG16.model', 'wb'))
```

### Using the latest feature (recommended)

Now you can load the saved model using `pickle` and fine-tune it.

Furthermore, recent Chainer has a useful functionality to load VGG16 and construct the Chainer model just one line:

```python
from chainer.links import VGG16Layers

model = VGG16Layers()
```

That's it! Please check [this PR](https://github.com/pfnet/chainer/pull/1677) and [the documentation](http://docs.chainer.org/en/stable/reference/links.html#pre-trained-models) (it also has ResNet50). This is way easier approach to use pre-trained models!

**Comment by apple2373** [comment]
Thanks. Wow, latter one looks so easy. I'll try that.

**Comment by hzhan11** [comment]
@mitmul , option1 "Load it using Caffe emulator of Chainer" will fail on my side as below. Any suggestion? Also, how about apply option 2 "Using the latest feature (recommended)" in train.py? how to adjust source code accordingly? Thanks! 

python train.py
2017-03-01 15:14:41,779 [INFO] sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
2017-03-01 15:14:41,779 [INFO] chainer version: 1.21.0
2017-03-01 15:14:41,780 [INFO] cuda: False, cudnn: False
2017-03-01 15:14:41,780 [INFO] Namespace(adam_alpha=0.001, adam_beta1=0.9, adam_beta2=0.999, adam_eps=1e-08, anchor_scales='8,16,32', batchsize=1, epoch=100, feat_stride=16, gpus='0', lr=0.01, lr_decay_freq=10, lr_decay_ratio=0.1, model_file='lib/models/faster_rcnn.py', model_name='FasterRCNN', n_anchors=9, n_classes=20, num_classes=21, opt='Adam', rpn_in_ch=512, rpn_out_ch=512, rpn_sigma=1.0, scale=0.5, scale_jitter=None, seed=1701, shift_jitter=None, show_log_iter=10, sigma=3.0, snapshot_iter=1000, spatial_scale=0.0625, train_anno_dir='data/VOCdevkit/VOC2007/Annotations', train_img_dir='data/VOCdevkit/VOC2007/JPEGImages', train_list_dir='data/VOCdevkit/VOC2007/ImageSets/Main', train_list_suffix='train', trunk_file='lib/models/vgg16.py', trunk_name='VGG16', trunk_param='data/VGG16.model', valid_anno_dir='data/VOCdevkit/VOC2007/Annotations', valid_batchsize=1, valid_freq=1, valid_img_dir='data/VOCdevkit/VOC2007/JPEGImages', valid_list_dir='data/VOCdevkit/VOC2007/ImageSets/Main', valid_list_suffix='val', weight_decay=0.0005)
2017-03-01 15:14:54,645 [INFO] Loading pre-trained trunk parameters...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    args.trunk_file, args.trunk_name, args.trunk_param, True, result_dir)
  File "/home/haoxiang/DL/chainer-faster-rcnn-master/utils/prepare_train.py", line 179, in get_model
    trunk = np.load(trunk_param)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 416, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file 'data/VGG16.model' as a pickle

**Comment by apple2373** [comment]
I don't think there is a copyright for weights so I am sharing to you: https://drive.google.com/open?id=0B046sNk0DhCDWmt6Wm9lSkFlNGM

**Comment by chengs2000** [comment]
model can not be trained.

Exactly followed the steps listed on the page for training (including creating VGG16.model using the method of old approach), the model can not be trained.

Here is the error to train: python train.py

2017-03-24 12:55:52,857 [INFO] Loading pre-trained trunk parameters...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    args.trunk_file, args.trunk_name, args.trunk_param, True, result_dir)
  File "/Users/gchen/faster_RCNN/chainer-faster-rcnn/utils/prepare_train.py", line 183, in get_model
    for trunk_name in trunk.keys():
AttributeError: 'CaffeFunction' object has no attribute 'keys'

Does anyone has a soltuion?

Thanks.

**Comment by mitmul** [comment]
I'm sorry for the inconvenience. Now I'm fixing problems reported here and in the other issues and planning to merge the `v2` branch as soon as possible. So please kindly wait for the update.

**Comment by mitmul** [comment]
@hzhan11 @chengs2000 Hi, thank you for trying this chainer-faster-rcnn codes. We've released the new clean & simple & reliable (it surely reproduced the paper result) version of Faster R-CNN inference & training codes as ChainerCV: https://github.com/pfnet/chainercv . I think the problem discussed here has been solved in ChainerCV. Please check the ChainerCV repo!
