### ISSUE TITLE
Problem with cuda when running forward.py

### ISSUE THREAD

**Issue by 1991viet** [mitmul/chainer-faster-rcnn#22]
Hi,
When I run the forward.py, the following error appear:
Traceback (most recent call last):
  File "forward.py", line 94, in <module>
    cls_score, bbox_pred = model(img, img_info)
  File "/chainer-faster-rcnn-2/models/faster_rcnn.py", line 117, in __call__
    proposals, probs = self.RPN(feature_map, img_info, gt_boxes)
  File "/chainer-faster-rcnn-2/models/region_proposal_network.py", line 124, in __call__
    rpn_cls_prob, rpn_bbox_pred, img_info)
  File "/chainer-faster-rcnn-2/models/proposal_layer.py", line 133, in __call__
    all_bbox = self._generate_all_bbox_use_array_info(rpn_bbox_pred)
  File "/chainer-faster-rcnn-2/models/proposal_layer.py", line 201, in _generate_all_bbox_use_array_info
    return self._generate_all_bbox(feat_h, feat_w, xp)
  File "/chainer-faster-rcnn-2/models/proposal_layer.py", line 217, in _generate_all_bbox
    if xp is cuda.cupy \
AttributeError: 'module' object has no attribute 'cupy'
Could you suggest what should I do for addressing it. Thank you so much

**Comment by 1991viet** [comment]
Sorry, I already resolved it. Please close the topic. Thanks
