### ISSUE TITLE
Cannot run due to compiler complains

### ISSUE THREAD

**Issue by ptuls** [mitmul/chainer-faster-rcnn#6]
Hi, 

I am running Chainer and this algorithm on an Ubuntu 16.04 environment on a GTX 970. It seems fine running with CPU, but with my GPU, I get the following errors:

`Traceback (most recent call last):
  File "forward.py", line 106, in <module>
    cls_score, bbox_pred = model(img, np.array([[h, w, im_scale]]))
  File "/home/cammy/repositories/cammy-skynet-benchmarking/faster-rcnn/lib/models/faster_rcnn.py", line 41, in __call__
    h, n = self.trunk(x), x.data.shape[0]
  File "/home/cammy/repositories/cammy-skynet-benchmarking/faster-rcnn/lib/models/VGG16.py", line 56, in __call__
    x = (getattr(self, name) if 'conv' in name else f)(x)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/convolution_2d.py", line 101, in __call__
    x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 318, in convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 198, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 310, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 103, in forward_gpu
    (self.ph, self.pw), (self.sy, self.sx), x.dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cudnn.py", line 101, in create_convolution_descriptor
    desc.value, pad[0], pad[1], stride[0], stride[1], 1, 1, mode)
  File "cupy/cuda/cudnn.pyx", line 348, in cupy.cuda.cudnn.setConvolution2dDescriptor (cupy/cuda/cudnn.cpp:3986)
TypeError: an integer is required`

Is there some problem in the code passing values into the convolutional layer? Thanks!

**Comment by mitmul** [comment]
@ptuls Hi, thank you for trying this chainer-faster-rcnn codes. We've released the new clean & simple & reliable (it surely reproduced the paper result) version of Faster R-CNN inference & training codes as ChainerCV: https://github.com/pfnet/chainercv . I think the error you faced has been fixed in ChainerCV. Please check the ChainerCV repo!
